server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useSSL=false&serverTimezone=UTC
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**
jwt:
  secret: thisisaverylongsecretkeyforjwt1234567890
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.hospital.api_gateway: DEBUG
  file:
    name: D:/Projects/microservices/api-gateway/app.log