server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG